/* Code automatically generated by maple */

#include "calc_fund_coeffs.h"

void calcFundLinCoeffs2(double m1[2],double m2[2],double eq[9])
{
  double t1;
  double t2;
  double t3;
  double t4;
  {
    t1 = m2[0];
    t2 = m1[0];
    eq[0] = t1*t2;
    t3 = m1[1];
    eq[1] = t1*t3;
    eq[2] = t1;
    t4 = m2[1];
    eq[3] = t2*t4;
    eq[4] = t4*t3;
    eq[5] = t4;
    eq[6] = t2;
    eq[7] = t3;
    eq[8] = 1.0;
    return;
  }
}

#include <math.h>
void calcEpipDist_12(double m1[2],double m2[2],double f8[8],double d[1])
{
  double t1;
  double t11;
  double t12;
  double t14;
  double t16;
  double t17;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t25;
  double t26;
  double t29;
  double t3;
  double t30;
  double t32;
  double t33;
  double t34;
  double t40;
  double t44;
  double t49;
  double t5;
  double t50;
  double t51;
  double t6;
  double t8;
  double t9;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = m1[0];
    t5 = f8[1];
    t6 = m1[1];
    t8 = f8[2];
    t9 = t2*t3+t5*t6+t8;
    t11 = m2[1];
    t12 = f8[3];
    t14 = f8[4];
    t16 = f8[5];
    t17 = t12*t3+t14*t6+t16;
    t19 = f8[6];
    t20 = t19*t2;
    t21 = f8[7];
    t22 = t12*t21;
    t25 = t19*t5;
    t26 = t14*t21;
    t29 = t19*t8;
    t30 = t21*t16;
    t32 = pow(t1*t9+t17*t11+(t20+t22)*t3+(t25+t26)*t6+t29+t30,2.0);
    t33 = t9*t9;
    t34 = t17*t17;
    t40 = t1*t2+t11*t12+t20+t22;
    t44 = t5*t1+t14*t11+t25+t26;
    t49 = pow(t3*t40+t6*t44+t8*t1+t16*t11+t29+t30,2.0);
    t50 = t40*t40;
    t51 = t44*t44;
    d[0] = t32/(t33+t34)+t49/(t50+t51);
    return;
  }
}

void calcEpipDistJac_12(double m1[2],double m2[2],double f8[8],double d_grad[8]
)
{
  double t1;
  double t11;
  double t12;
  double t14;
  double t16;
  double t17;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t25;
  double t26;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t36;
  double t41;
  double t42;
  double t44;
  double t49;
  double t5;
  double t53;
  double t57;
  double t58;
  double t59;
  double t6;
  double t60;
  double t62;
  double t63;
  double t66;
  double t67;
  double t69;
  double t8;
  double t9;
  double t96;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = m1[0];
    t5 = f8[1];
    t6 = m1[1];
    t8 = f8[2];
    t9 = t2*t3+t5*t6+t8;
    t11 = m2[1];
    t12 = f8[3];
    t14 = f8[4];
    t16 = f8[5];
    t17 = t12*t3+t14*t6+t16;
    t19 = f8[6];
    t20 = t19*t2;
    t21 = f8[7];
    t22 = t12*t21;
    t25 = t19*t5;
    t26 = t14*t21;
    t29 = t19*t8;
    t30 = t21*t16;
    t31 = t1*t9+t17*t11+(t20+t22)*t3+(t25+t26)*t6+t29+t30;
    t32 = t9*t9;
    t33 = t17*t17;
    t34 = t32+t33;
    t36 = t31/t34;
    t41 = t31*t31;
    t42 = t34*t34;
    t44 = t41/t42;
    t49 = t1*t2+t11*t12+t20+t22;
    t53 = t5*t1+t14*t11+t25+t26;
    t57 = t3*t49+t6*t53+t8*t1+t16*t11+t29+t30;
    t58 = t49*t49;
    t59 = t53*t53;
    t60 = t58+t59;
    t62 = t57/t60;
    t63 = t1+t19;
    t66 = t57*t57;
    t67 = t60*t60;
    t69 = t66/t67;
    d_grad[0] = 2.0*t36*(t3*t1+t19*t3)-2.0*t44*t9*t3+2.0*t62*t3*t63-2.0*t69*t49
*t63;
    d_grad[1] = 2.0*t36*(t1*t6+t19*t6)-2.0*t44*t9*t6+2.0*t62*t6*t63-2.0*t69*t53
*t63;
    d_grad[2] = 2.0*t36*t63-2.0*t44*t9+2.0*t62*t63;
    t96 = t11+t21;
    d_grad[3] = 2.0*t36*(t11*t3+t21*t3)-2.0*t44*t17*t3+2.0*t62*t3*t96-2.0*t69*
t49*t96;
    d_grad[4] = 2.0*t36*(t6*t11+t21*t6)-2.0*t44*t17*t6+2.0*t62*t6*t96-2.0*t69*
t53*t96;
    d_grad[5] = 2.0*t36*t96-2.0*t44*t17+2.0*t62*t96;
    d_grad[6] = 2.0*t36*t9+2.0*t62*t9-t69*(2.0*t49*t2+2.0*t53*t5);
    d_grad[7] = 2.0*t36*t17+2.0*t62*t17-t69*(2.0*t49*t12+2.0*t53*t14);
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDist_12(double m1[2],double m2[2],double f8[8],
double err[1])
{
  double t1;
  double t10;
  double t104;
  double t108;
  double t12;
  double t13;
  double t14;
  double t16;
  double t17;
  double t19;
  double t2;
  double t21;
  double t24;
  double t3;
  double t33;
  double t34;
  double t35;
  double t39;
  double t4;
  double t42;
  double t45;
  double t48;
  double t52;
  double t56;
  double t6;
  double t60;
  double t63;
  double t65;
  double t69;
  double t7;
  double t71;
  double t74;
  double t8;
  double t81;
  double t82;
  double t85;
  double t90;
  double t92;
  double t94;
  double t95;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = t1*t2;
    t4 = m1[0];
    t6 = f8[1];
    t7 = t1*t6;
    t8 = m1[1];
    t10 = f8[2];
    t12 = m2[1];
    t13 = f8[3];
    t14 = t13*t12;
    t16 = f8[4];
    t17 = t16*t12;
    t19 = f8[5];
    t21 = f8[6];
    t24 = f8[7];
    t33 = t3*t4+t7*t8+t1*t10+t4*t14+t17*t8+t19*t12+t4*t21*t2+t4*t24*t13+t8*t21*
t6+t8*t24*t16+t21*t10+t24*t19;
    t34 = t33*t33;
    t35 = t13*t13;
    t39 = t6*t8;
    t42 = t13*t4;
    t45 = t16*t8;
    t48 = t2*t2;
    t52 = t6*t6;
    t56 = t16*t16;
    t60 = t2*t4;
    t63 = t12*t12;
    t65 = t8*t8;
    t69 = t24*t24;
    t71 = t24*t13;
    t74 = t2*t21;
    t81 = 2.0*t35*t12*t24+2.0*t39*t10+2.0*t19*t42+2.0*t45*t19+2.0*t48*t1*t21+
2.0*t52*t1*t21+2.0*t56*t12*t24+2.0*t60*t10+t56*t63+t56*t65+2.0*t3*t14+t69*t56+
2.0*t71*t3+2.0*t14*t74+2.0*t74*t71+2.0*t7*t17;
    t82 = t24*t16;
    t85 = t21*t6;
    t90 = t1*t1;
    t92 = t19*t19;
    t94 = t10*t10;
    t95 = t4*t4;
    t104 = t21*t21;
    t108 = 2.0*t7*t82+2.0*t17*t85+2.0*t85*t82+t48*t90+t92+t35*t63+t94+t35*t95+
2.0*t60*t39+2.0*t42*t45+t48*t95+t65*t52+t52*t90+t104*t52+t104*t48+t69*t35;
    err[0] = sqrt(t34/(t81+t108));
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDistGrads_12(double m1[2],double m2[2],double f8[8],
double grads[8])
{
  double t1;
  double t10;
  double t106;
  double t107;
  double t108;
  double t109;
  double t110;
  double t112;
  double t113;
  double t114;
  double t119;
  double t12;
  double t121;
  double t13;
  double t135;
  double t14;
  double t140;
  double t16;
  double t17;
  double t182;
  double t19;
  double t2;
  double t203;
  double t21;
  double t22;
  double t24;
  double t248;
  double t25;
  double t27;
  double t29;
  double t3;
  double t33;
  double t34;
  double t35;
  double t36;
  double t38;
  double t39;
  double t4;
  double t41;
  double t42;
  double t44;
  double t47;
  double t50;
  double t53;
  double t56;
  double t57;
  double t6;
  double t60;
  double t63;
  double t65;
  double t68;
  double t7;
  double t72;
  double t73;
  double t76;
  double t78;
  double t8;
  double t80;
  double t91;
  double t92;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = t1*t2;
    t4 = m1[0];
    t6 = f8[1];
    t7 = t1*t6;
    t8 = m1[1];
    t10 = f8[2];
    t12 = m2[1];
    t13 = f8[3];
    t14 = t13*t12;
    t16 = f8[4];
    t17 = t16*t12;
    t19 = f8[5];
    t21 = f8[6];
    t22 = t4*t21;
    t24 = f8[7];
    t25 = t4*t24;
    t27 = t8*t21;
    t29 = t8*t24;
    t33 = t3*t4+t7*t8+t1*t10+t4*t14+t17*t8+t19*t12+t22*t2+t13*t25+t27*t6+t29*
t16+t21*t10+t24*t19;
    t34 = t33*t33;
    t35 = t6*t6;
    t36 = t1*t1;
    t38 = t16*t16;
    t39 = t12*t12;
    t41 = t24*t24;
    t42 = t13*t13;
    t44 = t42*t12;
    t47 = t6*t8;
    t50 = t13*t4;
    t53 = t16*t8;
    t56 = t2*t2;
    t57 = t56*t1;
    t60 = t35*t1;
    t63 = t21*t21;
    t65 = t38*t12;
    t68 = t2*t4;
    t72 = t2*t21;
    t73 = t24*t13;
    t76 = t4*t4;
    t78 = t8*t8;
    t80 = t35*t36+t38*t39+t41*t42+2.0*t44*t24+2.0*t47*t10+2.0*t50*t19+2.0*t53*
t19+2.0*t57*t21+2.0*t60*t21+t56*t63+2.0*t65*t24+2.0*t68*t10+t56*t36+2.0*t72*t73
+t56*t76+t35*t78;
    t91 = t21*t6;
    t92 = t24*t16;
    t106 = t10*t10;
    t107 = t19*t19;
    t108 = 2.0*t14*t72+2.0*t3*t73+2.0*t3*t14+t41*t38+t35*t63+2.0*t68*t47+2.0*
t91*t92+2.0*t17*t91+2.0*t7*t92+2.0*t7*t17+t42*t39+t38*t78+2.0*t50*t53+t42*t76+
t106+t107;
    t109 = t80+t108;
    t110 = 1/t109;
    t112 = sqrt(t34*t110);
    t113 = 1/t112;
    t114 = t110*t33;
    t119 = t109*t109;
    t121 = t34/t119;
    t135 = t24*t1;
    t140 = t21*t24;
    grads[0] = t113*(2.0*t114*(t4*t1+t22)-t121*(2.0*t4*t10+4.0*t3*t21+2.0*t2*
t36+2.0*t63*t2+2.0*t2*t76+2.0*t1*t13*t12+2.0*t135*t13+2.0*t14*t21+2.0*t140*t13+
2.0*t4*t6*t8))/2.0;
    grads[1] = t113*(2.0*t114*(t1*t8+t27)-t121*(4.0*t7*t21+2.0*t8*t10+2.0*t6*
t36+2.0*t63*t6+2.0*t6*t78+2.0*t1*t16*t12+2.0*t135*t16+2.0*t17*t21+2.0*t140*t16+
2.0*t68*t8))/2.0;
    t182 = t68+t47+t10;
    grads[2] = t113*(2.0*t114*(t1+t21)-2.0*t121*t182)/2.0;
    t203 = t12*t21;
    grads[3] = t113*(2.0*t114*(t12*t4+t25)-t121*(2.0*t4*t19+4.0*t14*t24+2.0*t41
*t13+2.0*t13*t39+2.0*t3*t12+2.0*t24*t3+2.0*t203*t2+2.0*t72*t24+2.0*t4*t16*t8+
2.0*t13*t76))/2.0;
    grads[4] = t113*(2.0*t114*(t12*t8+t29)-t121*(4.0*t17*t24+2.0*t8*t19+2.0*t16
*t39+2.0*t41*t16+2.0*t16*t78+2.0*t7*t12+2.0*t7*t24+2.0*t203*t6+2.0*t91*t24+2.0*
t50*t8))/2.0;
    t248 = t50+t53+t19;
    grads[5] = t113*(2.0*t114*(t12+t24)-2.0*t121*t248)/2.0;
    grads[6] = t113*(2.0*t114*t182-t121*(2.0*t60+2.0*t57+2.0*t21*t56+2.0*t21*
t35+2.0*t14*t2+2.0*t2*t24*t13+2.0*t17*t6+2.0*t6*t24*t16))/2.0;
    grads[7] = t113*(2.0*t114*t248-t121*(2.0*t65+2.0*t44+2.0*t24*t42+2.0*t24*
t38+2.0*t3*t13+2.0*t72*t13+2.0*t7*t16+2.0*t91*t16))/2.0;
    return;
  }
}

#include <math.h>
void calcEpipDist_13(double m1[2],double m2[2],double f8[8],double d[1])
{
  double t1;
  double t11;
  double t12;
  double t14;
  double t15;
  double t17;
  double t2;
  double t20;
  double t22;
  double t24;
  double t25;
  double t26;
  double t27;
  double t3;
  double t32;
  double t33;
  double t34;
  double t40;
  double t44;
  double t5;
  double t50;
  double t51;
  double t52;
  double t6;
  double t8;
  double t9;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = m1[0];
    t5 = f8[1];
    t6 = m1[1];
    t8 = f8[2];
    t9 = t3*t2+t5*t6+t8;
    t11 = m2[1];
    t12 = f8[6];
    t14 = f8[7];
    t15 = f8[3];
    t17 = t12*t2+t15*t14;
    t20 = f8[4];
    t22 = t12*t5+t14*t20;
    t24 = t12*t8;
    t25 = f8[5];
    t26 = t14*t25;
    t27 = t17*t3+t22*t6+t24+t26;
    t32 = pow(t9*t1+t11*t27+t15*t3+t20*t6+t25,2.0);
    t33 = t9*t9;
    t34 = t27*t27;
    t40 = t1*t2+t17*t11+t15;
    t44 = t5*t1+t22*t11+t20;
    t50 = pow(t3*t40+t44*t6+t1*t8+(t24+t26)*t11+t25,2.0);
    t51 = t40*t40;
    t52 = t44*t44;
    d[0] = t32/(t33+t34)+t50/(t51+t52);
    return;
  }
}

void calcEpipDistJac_13(double m1[2],double m2[2],double f8[8],double d_grad[8]
)
{
  double t1;
  double t104;
  double t108;
  double t11;
  double t111;
  double t12;
  double t14;
  double t15;
  double t150;
  double t17;
  double t2;
  double t20;
  double t22;
  double t24;
  double t25;
  double t26;
  double t27;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t36;
  double t38;
  double t4;
  double t43;
  double t44;
  double t46;
  double t48;
  double t5;
  double t55;
  double t59;
  double t6;
  double t64;
  double t65;
  double t66;
  double t67;
  double t69;
  double t7;
  double t70;
  double t74;
  double t75;
  double t77;
  double t8;
  double t9;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = m1[0];
    t4 = t3*t2;
    t5 = f8[1];
    t6 = m1[1];
    t7 = t5*t6;
    t8 = f8[2];
    t9 = t4+t7+t8;
    t11 = m2[1];
    t12 = f8[6];
    t14 = f8[7];
    t15 = f8[3];
    t17 = t12*t2+t15*t14;
    t20 = f8[4];
    t22 = t12*t5+t14*t20;
    t24 = t12*t8;
    t25 = f8[5];
    t26 = t14*t25;
    t27 = t17*t3+t22*t6+t24+t26;
    t29 = t15*t3;
    t30 = t20*t6;
    t31 = t9*t1+t11*t27+t29+t30+t25;
    t32 = t9*t9;
    t33 = t27*t27;
    t34 = t32+t33;
    t36 = t31/t34;
    t38 = t12*t11;
    t43 = t31*t31;
    t44 = t34*t34;
    t46 = t43/t44;
    t48 = t27*t12;
    t55 = t1*t2+t17*t11+t15;
    t59 = t5*t1+t22*t11+t20;
    t64 = t3*t55+t59*t6+t1*t8+(t24+t26)*t11+t25;
    t65 = t55*t55;
    t66 = t59*t59;
    t67 = t65+t66;
    t69 = t64/t67;
    t70 = t1+t38;
    t74 = t64*t64;
    t75 = t67*t67;
    t77 = t74/t75;
    d_grad[0] = 2.0*t36*(t1*t3+t3*t38)-t46*(2.0*t3*t9+2.0*t48*t3)+2.0*t69*t3*
t70-2.0*t77*t55*t70;
    d_grad[1] = 2.0*t36*(t1*t6+t38*t6)-t46*(2.0*t9*t6+2.0*t48*t6)+2.0*t69*t6*
t70-2.0*t77*t59*t70;
    d_grad[2] = 2.0*t36*t70-t46*(2.0*t4+2.0*t7+2.0*t8+2.0*t48)+2.0*t69*t70;
    t104 = t11*t14;
    t108 = t27*t14;
    t111 = t104+1.0;
    d_grad[3] = 2.0*t36*(t3*t104+t3)-2.0*t46*t108*t3+2.0*t69*t3*t111-2.0*t77*
t55*t111;
    d_grad[4] = 2.0*t36*(t104*t6+t6)-2.0*t46*t108*t6+2.0*t69*t6*t111-2.0*t77*
t59*t111;
    d_grad[5] = 2.0*t36*t111-2.0*t46*t108+2.0*t69*t111;
    d_grad[6] = 2.0*t36*t11*t9-2.0*t46*t27*t9+2.0*t69*(t4*t11+t7*t11+t8*t11)-
t77*(2.0*t55*t2*t11+2.0*t59*t5*t11);
    t150 = t29+t30+t25;
    d_grad[7] = 2.0*t36*t11*t150-2.0*t46*t27*t150+2.0*t69*(t11*t15*t3+t11*t20*
t6+t25*t11)-t77*(2.0*t55*t15*t11+2.0*t59*t20*t11);
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDist_13(double m1[2],double m2[2],double f8[8],
double err[1])
{
  double t1;
  double t10;
  double t102;
  double t106;
  double t112;
  double t119;
  double t12;
  double t124;
  double t127;
  double t13;
  double t130;
  double t134;
  double t138;
  double t14;
  double t141;
  double t15;
  double t166;
  double t17;
  double t18;
  double t2;
  double t21;
  double t22;
  double t24;
  double t27;
  double t3;
  double t30;
  double t34;
  double t35;
  double t36;
  double t4;
  double t40;
  double t43;
  double t44;
  double t46;
  double t48;
  double t50;
  double t52;
  double t54;
  double t58;
  double t59;
  double t6;
  double t7;
  double t70;
  double t71;
  double t77;
  double t8;
  double t80;
  double t83;
  double t88;
  double t90;
  double t94;
  double t96;
  double t97;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = t1*t2;
    t4 = m1[0];
    t6 = f8[1];
    t7 = t1*t6;
    t8 = m1[1];
    t10 = f8[2];
    t12 = m2[1];
    t13 = t12*t4;
    t14 = f8[6];
    t15 = t14*t2;
    t17 = f8[7];
    t18 = f8[3];
    t21 = t12*t8;
    t22 = t14*t6;
    t24 = f8[4];
    t27 = t14*t12;
    t30 = f8[5];
    t34 = t3*t4+t7*t8+t1*t10+t13*t15+t13*t17*t18+t21*t22+t21*t17*t24+t27*t10+
t12*t17*t30+t18*t4+t24*t8+t30;
    t35 = t34*t34;
    t36 = t24*t24;
    t40 = t2*t4;
    t43 = t8*t8;
    t44 = t14*t14;
    t46 = t6*t6;
    t48 = t4*t4;
    t50 = t2*t2;
    t52 = t17*t17;
    t54 = t18*t18;
    t58 = t12*t12;
    t59 = t44*t58;
    t70 = 2.0*t36*t12*t17+2.0*t40*t10+t43*t44*t46+t48*t44*t50+t48*t52*t54+t43*
t52*t36+t59*t46+t36*t58*t52+2.0*t3*t18+2.0*t7*t24+2.0*t54*t12*t17;
    t71 = t6*t8;
    t77 = t10*t10;
    t80 = t1*t1;
    t83 = t4*t52;
    t88 = t4*t17;
    t90 = t14*t8;
    t94 = 2.0*t71*t10+t50*t59+t54*t52*t58+t54+t36+t77+t46*t43+t50*t48+t50*t80+
t46*t80+2.0*t83*t18*t8*t24+2.0*t88*t18*t90*t6;
    t96 = t4*t14;
    t97 = t2*t17;
    t102 = t17*t8;
    t106 = t4*t44;
    t112 = t97*t18;
    t119 = t6*t17;
    t124 = t119*t24;
    t127 = t58*t14;
    t130 = t18*t12;
    t134 = t12*t24;
    t138 = t30*t30;
    t141 = 2.0*t96*t97*t30+2.0*t96*t2*t102*t24+2.0*t106*t2*t8*t6+2.0*t48*t14*
t112+2.0*t102*t24*t14*t10+2.0*t90*t119*t30+2.0*t43*t14*t124+2.0*t127*t124+2.0*
t3*t130*t17+2.0*t7*t134*t17+t52*t138+t44*t77;
    t166 = t88*t18*t14*t10+t127*t112+t50*t1*t27+t40*t71+t134*t22+t15*t130+t83*
t18*t30+t106*t2*t10+t46*t1*t27+t14*t10*t17*t30+t8*t52*t24*t30+t8*t44*t6*t10;
    err[0] = sqrt(t35/(t70+t94+t141+2.0*t166));
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDistGrads_13(double m1[2],double m2[2],double f8[8],
double grads[8])
{
  double t1;
  double t10;
  double t100;
  double t102;
  double t105;
  double t107;
  double t109;
  double t110;
  double t111;
  double t114;
  double t117;
  double t12;
  double t120;
  double t121;
  double t124;
  double t125;
  double t128;
  double t129;
  double t13;
  double t133;
  double t135;
  double t136;
  double t139;
  double t14;
  double t140;
  double t141;
  double t144;
  double t148;
  double t15;
  double t151;
  double t152;
  double t155;
  double t156;
  double t159;
  double t163;
  double t166;
  double t167;
  double t168;
  double t17;
  double t177;
  double t179;
  double t18;
  double t181;
  double t182;
  double t184;
  double t185;
  double t186;
  double t19;
  double t192;
  double t194;
  double t199;
  double t2;
  double t205;
  double t21;
  double t22;
  double t228;
  double t239;
  double t24;
  double t245;
  double t25;
  double t27;
  double t270;
  double t29;
  double t3;
  double t30;
  double t317;
  double t32;
  double t33;
  double t34;
  double t35;
  double t350;
  double t36;
  double t387;
  double t39;
  double t4;
  double t40;
  double t417;
  double t43;
  double t434;
  double t44;
  double t441;
  double t45;
  double t46;
  double t469;
  double t48;
  double t49;
  double t50;
  double t52;
  double t55;
  double t6;
  double t62;
  double t64;
  double t66;
  double t67;
  double t69;
  double t7;
  double t70;
  double t73;
  double t78;
  double t8;
  double t81;
  double t84;
  double t85;
  double t88;
  double t89;
  double t92;
  double t93;
  double t96;
  double t98;
  {
    t1 = m2[0];
    t2 = f8[0];
    t3 = t1*t2;
    t4 = m1[0];
    t6 = f8[1];
    t7 = t1*t6;
    t8 = m1[1];
    t10 = f8[2];
    t12 = m2[1];
    t13 = t12*t4;
    t14 = f8[6];
    t15 = t14*t2;
    t17 = f8[7];
    t18 = f8[3];
    t19 = t17*t18;
    t21 = t12*t8;
    t22 = t14*t6;
    t24 = f8[4];
    t25 = t17*t24;
    t27 = t14*t12;
    t29 = t12*t17;
    t30 = f8[5];
    t32 = t18*t4;
    t33 = t24*t8;
    t34 = t3*t4+t7*t8+t1*t10+t13*t15+t13*t19+t21*t22+t21*t25+t27*t10+t29*t30+
t32+t33+t30;
    t35 = t34*t34;
    t36 = t2*t4;
    t39 = t24*t24;
    t40 = t39*t12;
    t43 = t18*t18;
    t44 = t12*t12;
    t45 = t43*t44;
    t46 = t17*t17;
    t48 = t14*t14;
    t49 = t44*t48;
    t50 = t2*t2;
    t52 = t6*t8;
    t55 = t43*t12;
    t62 = t39*t44;
    t64 = t6*t6;
    t66 = t8*t8;
    t67 = t66*t46;
    t69 = 2.0*t36*t10+2.0*t40*t17+t45*t46+t49*t50+2.0*t52*t10+2.0*t55*t17+2.0*
t7*t24+2.0*t3*t18+t62*t46+t49*t64+t67*t39;
    t70 = t18*t12;
    t73 = t12*t24;
    t78 = t50*t1;
    t81 = t64*t1;
    t84 = t4*t48;
    t85 = t2*t10;
    t88 = t4*t46;
    t89 = t18*t30;
    t92 = t8*t48;
    t93 = t6*t10;
    t96 = t10*t10;
    t98 = t4*t4;
    t100 = t1*t1;
    t102 = 2.0*t70*t15+2.0*t73*t22+2.0*t36*t52+2.0*t78*t27+2.0*t81*t27+2.0*t84*
t85+2.0*t88*t89+2.0*t92*t93+t96+t64*t66+t50*t98+t64*t100;
    t105 = t98*t46;
    t107 = t98*t48;
    t109 = t44*t14;
    t110 = t2*t18;
    t111 = t110*t17;
    t114 = t70*t17;
    t117 = t73*t17;
    t120 = t8*t46;
    t121 = t24*t30;
    t124 = t14*t10;
    t125 = t17*t30;
    t128 = t4*t14;
    t129 = t2*t17;
    t133 = t4*t17;
    t135 = t14*t8;
    t136 = t135*t6;
    t139 = t50*t100+t105*t43+t107*t50+t43+t39+2.0*t109*t111+2.0*t3*t114+2.0*t7*
t117+2.0*t120*t121+2.0*t124*t125+2.0*t128*t129*t30+2.0*t133*t18*t136;
    t140 = t18*t8;
    t141 = t140*t24;
    t144 = t18*t14;
    t148 = t66*t48;
    t151 = t17*t8;
    t152 = t151*t24;
    t155 = t2*t8;
    t156 = t155*t6;
    t159 = t24*t14;
    t163 = t98*t14;
    t166 = t66*t14;
    t167 = t6*t17;
    t168 = t167*t24;
    t177 = t30*t30;
    t179 = 2.0*t88*t141+2.0*t133*t144*t10+t148*t64+2.0*t128*t2*t152+2.0*t84*
t156+2.0*t151*t159*t10+2.0*t111*t163+2.0*t166*t168+2.0*t109*t168+2.0*t135*t167*
t30+t48*t96+t46*t177;
    t181 = t69+t102+t139+t179;
    t182 = 1/t181;
    t184 = sqrt(t35*t182);
    t185 = 1/t184;
    t186 = t34*t182;
    t192 = t181*t181;
    t194 = t35/t192;
    t199 = t1*t18;
    t205 = t2*t98;
    t228 = 2.0*t4*t10+2.0*t49*t2+2.0*t199+2.0*t107*t2+2.0*t2*t100+2.0*t205+2.0*
t70*t14+2.0*t4*t6*t8+4.0*t3*t27+2.0*t163*t19+2.0*t84*t52+2.0*t128*t152+2.0*t128
*t125+2.0*t84*t10+2.0*t199*t29+2.0*t109*t19;
    grads[0] = t185*(2.0*t186*(t1*t4+t27*t4)-t194*t228)/2.0;
    t239 = t1*t24;
    t245 = t6*t66;
    t270 = 2.0*t8*t10+2.0*t239+2.0*t49*t6+2.0*t6*t100+2.0*t245+2.0*t73*t14+2.0*
t36*t8+4.0*t7*t27+2.0*t109*t25+2.0*t166*t25+2.0*t125*t135+2.0*t84*t155+2.0*t133
*t140*t14+2.0*t148*t6+2.0*t92*t10+2.0*t239*t29;
    grads[1] = t185*(2.0*t186*(t1*t8+t27*t8)-t194*t270)/2.0;
    grads[2] = t185*(2.0*t186*(t1+t27)-t194*(2.0*t36+2.0*t52+2.0*t10+2.0*t159*
t151+2.0*t133*t144+2.0*t48*t10+2.0*t84*t2+2.0*t92*t6+2.0*t14*t17*t30))/2.0;
    t317 = 2.0*t18*t44*t46+4.0*t114+2.0*t3+2.0*t105*t18+2.0*t18+2.0*t27*t2+2.0*
t163*t129+2.0*t133*t136+2.0*t88*t33+2.0*t124*t133+2.0*t88*t30+2.0*t3*t29+2.0*
t109*t129;
    grads[3] = t185*(2.0*t186*(t29*t4+t4)-t194*t317)/2.0;
    t350 = 4.0*t117+2.0*t24+2.0*t7+2.0*t24*t44*t46+2.0*t67*t24+2.0*t27*t6+2.0*
t109*t167+2.0*t166*t167+2.0*t151*t124+2.0*t128*t155*t17+2.0*t88*t140+2.0*t120*
t30+2.0*t7*t29;
    grads[4] = t185*(2.0*t186*(t29*t8+t8)-t194*t350)/2.0;
    grads[5] = t185*(2.0*t186*(t29+1.0)-t194*(2.0*t167*t135+2.0*t128*t129+2.0*
t88*t18+2.0*t120*t24+2.0*t124*t17+2.0*t46*t30))/2.0;
    t387 = t109*t50+t109*t64+t163*t50+t70*t2+t73*t6+t78*t12+t81*t12+t44*t6*t25+
t245*t25+t52*t125+t151*t24*t10;
    t417 = 2.0*t205*t19+4.0*t128*t156+2.0*t36*t152+2.0*t36*t125+2.0*t133*t140*
t6+2.0*t133*t18*t10+2.0*t166*t64+2.0*t14*t96+4.0*t128*t85+4.0*t135*t93+2.0*t10*
t17*t30+2.0*t44*t2*t19;
    grads[6] = t185*(2.0*t186*(t36*t12+t52*t12+t12*t10)-t194*(2.0*t387+t417))/
2.0;
    t434 = t6*t24;
    t441 = t40+t45*t17+t55+t62*t17+t66*t17*t39+t98*t17*t43+t109*t434+t166*t434+
t135*t6*t30+t33*t124+t163*t110;
    t469 = 2.0*t128*t155*t24+2.0*t128*t2*t30+2.0*t32*t136+4.0*t141*t133+2.0*t32
*t124+4.0*t133*t89+4.0*t151*t121+2.0*t124*t30+2.0*t17*t177+2.0*t7*t73+2.0*t3*
t70+2.0*t109*t110;
    grads[7] = t185*(2.0*t186*(t70*t4+t73*t8+t30*t12)-t194*(2.0*t441+t469))/2.0
;
    return;
  }
}

#include <math.h>
void calcEpipDist_23(double m1[2],double m2[2],double f8[8],double d[1])
{
  double t1;
  double t11;
  double t13;
  double t15;
  double t16;
  double t18;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t24;
  double t27;
  double t3;
  double t32;
  double t33;
  double t34;
  double t40;
  double t44;
  double t5;
  double t50;
  double t51;
  double t52;
  double t6;
  double t8;
  double t9;
  {
    t1 = m2[0];
    t2 = f8[6];
    t3 = f8[0];
    t5 = f8[7];
    t6 = f8[3];
    t8 = t2*t3+t5*t6;
    t9 = m1[0];
    t11 = f8[1];
    t13 = f8[4];
    t15 = t2*t11+t13*t5;
    t16 = m1[1];
    t18 = f8[2];
    t19 = t2*t18;
    t20 = f8[5];
    t21 = t5*t20;
    t22 = t8*t9+t16*t15+t19+t21;
    t24 = m2[1];
    t27 = t9*t3+t16*t11+t18;
    t32 = pow(t22*t1+t24*t27+t6*t9+t16*t13+t20,2.0);
    t33 = t27*t27;
    t34 = t22*t22;
    t40 = t1*t8+t3*t24+t6;
    t44 = t1*t15+t24*t11+t13;
    t50 = pow(t9*t40+t16*t44+(t19+t21)*t1+t24*t18+t20,2.0);
    t51 = t40*t40;
    t52 = t44*t44;
    d[0] = t32/(t33+t34)+t50/(t51+t52);
    return;
  }
}

void calcEpipDistJac_23(double m1[2],double m2[2],double f8[8],double d_grad[8]
)
{
  double t1;
  double t104;
  double t108;
  double t11;
  double t111;
  double t13;
  double t15;
  double t152;
  double t16;
  double t18;
  double t19;
  double t2;
  double t20;
  double t21;
  double t22;
  double t24;
  double t25;
  double t26;
  double t27;
  double t29;
  double t3;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t36;
  double t37;
  double t43;
  double t44;
  double t46;
  double t48;
  double t5;
  double t55;
  double t59;
  double t6;
  double t64;
  double t65;
  double t66;
  double t67;
  double t69;
  double t70;
  double t74;
  double t75;
  double t77;
  double t8;
  double t9;
  {
    t1 = m2[0];
    t2 = f8[6];
    t3 = f8[0];
    t5 = f8[7];
    t6 = f8[3];
    t8 = t2*t3+t5*t6;
    t9 = m1[0];
    t11 = f8[1];
    t13 = f8[4];
    t15 = t2*t11+t13*t5;
    t16 = m1[1];
    t18 = f8[2];
    t19 = t2*t18;
    t20 = f8[5];
    t21 = t5*t20;
    t22 = t8*t9+t16*t15+t19+t21;
    t24 = m2[1];
    t25 = t9*t3;
    t26 = t16*t11;
    t27 = t25+t26+t18;
    t29 = t6*t9;
    t30 = t16*t13;
    t31 = t22*t1+t24*t27+t29+t30+t20;
    t32 = t27*t27;
    t33 = t22*t22;
    t34 = t32+t33;
    t36 = t31/t34;
    t37 = t1*t2;
    t43 = t31*t31;
    t44 = t34*t34;
    t46 = t43/t44;
    t48 = t22*t2;
    t55 = t1*t8+t3*t24+t6;
    t59 = t1*t15+t24*t11+t13;
    t64 = t55*t9+t16*t59+(t19+t21)*t1+t24*t18+t20;
    t65 = t55*t55;
    t66 = t59*t59;
    t67 = t66+t65;
    t69 = t64/t67;
    t70 = t37+t24;
    t74 = t64*t64;
    t75 = t67*t67;
    t77 = t74/t75;
    d_grad[0] = 2.0*t36*(t37*t9+t24*t9)-t46*(2.0*t27*t9+2.0*t48*t9)+2.0*t69*t9*
t70-2.0*t77*t55*t70;
    d_grad[1] = 2.0*t36*(t37*t16+t16*t24)-t46*(2.0*t27*t16+2.0*t48*t16)+2.0*t69
*t16*t70-2.0*t77*t59*t70;
    d_grad[2] = 2.0*t36*t70-t46*(2.0*t25+2.0*t26+2.0*t18+2.0*t48)+2.0*t69*t70;
    t104 = t1*t5;
    t108 = t22*t5;
    t111 = t104+1.0;
    d_grad[3] = 2.0*t36*(t104*t9+t9)-2.0*t46*t108*t9+2.0*t69*t9*t111-2.0*t77*
t55*t111;
    d_grad[4] = 2.0*t36*(t16*t104+t16)-2.0*t46*t108*t16+2.0*t69*t16*t111-2.0*
t77*t59*t111;
    d_grad[5] = 2.0*t36*t111-2.0*t46*t108+2.0*t69*t111;
    d_grad[6] = 2.0*t36*t1*t27-2.0*t46*t22*t27+2.0*t69*(t1*t3*t9+t1*t11*t16+t18
*t1)-t77*(2.0*t55*t3*t1+2.0*t59*t11*t1);
    t152 = t29+t30+t20;
    d_grad[7] = 2.0*t36*t1*t152-2.0*t46*t22*t152+2.0*t69*(t9*t1*t6+t16*t1*t13+
t1*t20)-t77*(2.0*t55*t1*t6+2.0*t59*t1*t13);
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDist_23(double m1[2],double m2[2],double f8[8],
double err[1])
{
  double t1;
  double t100;
  double t105;
  double t106;
  double t111;
  double t115;
  double t12;
  double t122;
  double t13;
  double t131;
  double t138;
  double t14;
  double t142;
  double t146;
  double t147;
  double t158;
  double t17;
  double t181;
  double t2;
  double t21;
  double t23;
  double t24;
  double t26;
  double t27;
  double t29;
  double t3;
  double t34;
  double t35;
  double t4;
  double t40;
  double t41;
  double t43;
  double t45;
  double t47;
  double t49;
  double t5;
  double t50;
  double t52;
  double t54;
  double t58;
  double t60;
  double t62;
  double t64;
  double t74;
  double t77;
  double t78;
  double t8;
  double t82;
  double t88;
  double t9;
  double t92;
  double t95;
  {
    t1 = m2[0];
    t2 = m1[0];
    t3 = t1*t2;
    t4 = f8[6];
    t5 = f8[0];
    t8 = f8[7];
    t9 = f8[3];
    t12 = m1[1];
    t13 = t1*t12;
    t14 = f8[1];
    t17 = f8[4];
    t21 = f8[2];
    t23 = t1*t8;
    t24 = f8[5];
    t26 = t2*t5;
    t27 = m2[1];
    t29 = t12*t14;
    t34 = t3*t4*t5+t3*t8*t9+t13*t4*t14+t13*t8*t17+t1*t4*t21+t23*t24+t26*t27+t29
*t27+t21*t27+t9*t2+t17*t12+t24;
    t35 = t34*t34;
    t40 = t2*t2;
    t41 = t8*t8;
    t43 = t9*t9;
    t45 = t12*t12;
    t47 = t17*t17;
    t49 = t5*t5;
    t50 = t1*t1;
    t52 = t4*t4;
    t54 = t50*t41;
    t58 = t21*t21;
    t60 = t14*t14;
    t62 = 2.0*t21*t29+2.0*t26*t21+t40*t41*t43+t45*t41*t47+t49*t50*t52+t47*t54+
t40*t52*t49+t58+t40*t49+t60*t45+t43;
    t64 = t4*t8;
    t74 = t27*t27;
    t77 = t2*t8;
    t78 = t4*t9;
    t82 = t41*t2;
    t88 = t12*t4;
    t92 = t17*t27;
    t95 = t27*t9;
    t100 = t47+2.0*t5*t50*t64*t9+2.0*t14*t50*t64*t17+t45*t52*t60+t49*t74+t60*
t74+2.0*t77*t78*t21+2.0*t82*t9*t12*t17+2.0*t77*t9*t88*t14+2.0*t92*t14+2.0*t95*
t5+2.0*t23*t47;
    t105 = t2*t4;
    t106 = t5*t8;
    t111 = t12*t8;
    t115 = t52*t2;
    t122 = t4*t17;
    t131 = t8*t14;
    t138 = t1*t5;
    t142 = t1*t14;
    t146 = t54*t43+2.0*t23*t43+2.0*t105*t106*t24+2.0*t105*t5*t111*t17+2.0*t115*
t5*t12*t14+t60*t50*t52+2.0*t111*t122*t21+2.0*t40*t4*t106*t9+2.0*t45*t4*t131*t17
+2.0*t88*t131*t24+2.0*t138*t95*t8+2.0*t142*t92*t8;
    t147 = t24*t24;
    t158 = t4*t27;
    t181 = t41*t147+t52*t58+2.0*t26*t29+2.0*t115*t5*t21+2.0*t142*t122+2.0*t60*
t1*t158+2.0*t49*t1*t158+2.0*t138*t78+2.0*t12*t52*t14*t21+2.0*t82*t9*t24+2.0*t4*
t21*t8*t24+2.0*t12*t41*t17*t24;
    err[0] = sqrt(t35/(t62+t100+t146+t181));
    return;
  }
}

#include <math.h>
void calcEpipConstrSampsonDistGrads_23(double m1[2],double m2[2],double f8[8],
double grads[8])
{
  double t1;
  double t10;
  double t100;
  double t103;
  double t105;
  double t106;
  double t109;
  double t110;
  double t111;
  double t114;
  double t118;
  double t119;
  double t12;
  double t120;
  double t123;
  double t127;
  double t128;
  double t13;
  double t135;
  double t139;
  double t14;
  double t140;
  double t144;
  double t145;
  double t149;
  double t152;
  double t155;
  double t158;
  double t159;
  double t162;
  double t163;
  double t166;
  double t167;
  double t17;
  double t170;
  double t179;
  double t18;
  double t181;
  double t183;
  double t184;
  double t186;
  double t187;
  double t188;
  double t194;
  double t196;
  double t2;
  double t20;
  double t203;
  double t21;
  double t212;
  double t228;
  double t23;
  double t232;
  double t24;
  double t243;
  double t26;
  double t27;
  double t274;
  double t29;
  double t3;
  double t32;
  double t321;
  double t33;
  double t34;
  double t35;
  double t355;
  double t38;
  double t39;
  double t390;
  double t4;
  double t42;
  double t420;
  double t43;
  double t435;
  double t44;
  double t447;
  double t47;
  double t476;
  double t48;
  double t5;
  double t51;
  double t52;
  double t54;
  double t55;
  double t57;
  double t62;
  double t63;
  double t64;
  double t65;
  double t67;
  double t68;
  double t70;
  double t72;
  double t74;
  double t76;
  double t8;
  double t83;
  double t85;
  double t88;
  double t9;
  double t91;
  double t94;
  double t99;
  {
    t1 = m2[0];
    t2 = m1[0];
    t3 = t1*t2;
    t4 = f8[6];
    t5 = f8[0];
    t8 = f8[7];
    t9 = f8[3];
    t10 = t8*t9;
    t12 = m1[1];
    t13 = t1*t12;
    t14 = f8[1];
    t17 = f8[4];
    t18 = t8*t17;
    t20 = t1*t4;
    t21 = f8[2];
    t23 = t1*t8;
    t24 = f8[5];
    t26 = t2*t5;
    t27 = m2[1];
    t29 = t12*t14;
    t32 = t9*t2;
    t33 = t17*t12;
    t34 = t3*t4*t5+t3*t10+t13*t4*t14+t13*t18+t21*t20+t23*t24+t26*t27+t29*t27+
t21*t27+t32+t33+t24;
    t35 = t34*t34;
    t38 = t1*t5;
    t39 = t4*t9;
    t42 = t5*t5;
    t43 = t42*t1;
    t44 = t4*t27;
    t47 = t14*t14;
    t48 = t47*t1;
    t51 = t21*t21;
    t52 = t12*t12;
    t54 = t9*t9;
    t55 = t2*t2;
    t57 = t17*t17;
    t62 = 2.0*t26*t29+2.0*t38*t39+2.0*t43*t44+2.0*t48*t44+t51+t47*t52+t54+t42*
t55+t57+2.0*t26*t21+2.0*t21*t29;
    t63 = t1*t1;
    t64 = t42*t63;
    t65 = t4*t4;
    t67 = t8*t8;
    t68 = t52*t67;
    t70 = t55*t67;
    t72 = t55*t65;
    t74 = t63*t67;
    t76 = t47*t63;
    t83 = t52*t65;
    t85 = t27*t9;
    t88 = t17*t27;
    t91 = t64*t65+t68*t57+t70*t54+t72*t42+t74*t57+t76*t65+2.0*t23*t54+t74*t54+
2.0*t23*t57+t83*t47+2.0*t85*t5+2.0*t88*t14;
    t94 = t2*t8;
    t99 = t12*t4;
    t100 = t99*t14;
    t103 = t2*t4;
    t105 = t12*t8;
    t106 = t105*t17;
    t109 = t2*t65;
    t110 = t5*t12;
    t111 = t110*t14;
    t114 = t5*t8;
    t118 = t2*t67;
    t119 = t9*t12;
    t120 = t119*t17;
    t123 = t55*t4;
    t127 = t52*t4;
    t128 = t8*t14;
    t135 = t4*t17;
    t139 = t14*t63;
    t140 = t4*t8;
    t144 = t65*t51+2.0*t94*t39*t21+2.0*t94*t9*t100+2.0*t103*t5*t106+2.0*t109*
t111+2.0*t103*t114*t24+2.0*t118*t120+2.0*t123*t114*t9+2.0*t127*t128*t17+2.0*t99
*t128*t24+2.0*t105*t135*t21+2.0*t139*t140*t17;
    t145 = t5*t63;
    t149 = t1*t14;
    t152 = t5*t21;
    t155 = t9*t24;
    t158 = t12*t65;
    t159 = t14*t21;
    t162 = t12*t67;
    t163 = t17*t24;
    t166 = t4*t21;
    t167 = t8*t24;
    t170 = t27*t27;
    t179 = t24*t24;
    t181 = 2.0*t145*t140*t9+2.0*t149*t135+2.0*t109*t152+2.0*t118*t155+2.0*t158*
t159+2.0*t162*t163+2.0*t166*t167+t47*t170+t42*t170+2.0*t149*t88*t8+2.0*t38*t85*
t8+t67*t179;
    t183 = t62+t91+t144+t181;
    t184 = 1/t183;
    t186 = sqrt(t35*t184);
    t187 = 1/t186;
    t188 = t34*t184;
    t194 = t183*t183;
    t196 = t35/t194;
    t203 = t5*t55;
    t212 = t63*t4;
    t228 = t27*t8;
    t232 = 2.0*t2*t21+2.0*t145*t65+2.0*t72*t5+2.0*t203+2.0*t2*t14*t12+2.0*t20*
t9+4.0*t38*t44+2.0*t212*t10+2.0*t5*t170+2.0*t10*t123+2.0*t109*t29+2.0*t106*t103
+2.0*t103*t167+2.0*t109*t21+2.0*t1*t9*t228+2.0*t85;
    grads[0] = t187*(2.0*t188*(t2*t20+t27*t2)-t196*t232)/2.0;
    t243 = t14*t52;
    t274 = 2.0*t12*t21+2.0*t243+2.0*t26*t12+2.0*t139*t65+2.0*t14*t170+4.0*t149*
t44+2.0*t17*t20+2.0*t212*t18+2.0*t127*t18+2.0*t99*t167+2.0*t109*t110+2.0*t94*
t119*t4+2.0*t83*t14+2.0*t158*t21+2.0*t1*t17*t228+2.0*t88;
    grads[1] = t187*(2.0*t188*(t20*t12+t27*t12)-t196*t274)/2.0;
    grads[2] = t187*(2.0*t188*(t20+t27)-t196*(2.0*t26+2.0*t29+2.0*t21+2.0*t105*
t135+2.0*t94*t39+2.0*t65*t21+2.0*t109*t5+2.0*t158*t14+2.0*t140*t24))/2.0;
    t321 = 2.0*t70*t9+2.0*t9+2.0*t38*t4+4.0*t23*t9+2.0*t74*t9+2.0*t145*t140+2.0
*t114*t123+2.0*t94*t100+2.0*t118*t33+2.0*t94*t166+2.0*t118*t24+2.0*t38*t228+2.0
*t5*t27;
    grads[3] = t187*(2.0*t188*(t23*t2+t2)-t196*t321)/2.0;
    t355 = 2.0*t17+2.0*t68*t17+2.0*t74*t17+4.0*t23*t17+2.0*t4*t149+2.0*t139*
t140+2.0*t128*t127+2.0*t105*t166+2.0*t103*t110*t8+2.0*t118*t119+2.0*t162*t24+
2.0*t149*t228+2.0*t27*t14;
    grads[4] = t187*(2.0*t188*(t23*t12+t12)-t196*t355)/2.0;
    grads[5] = t187*(2.0*t188*(t23+1.0)-t196*(2.0*t128*t99+2.0*t114*t103+2.0*
t118*t9+2.0*t17*t162+2.0*t166*t8+2.0*t67*t24))/2.0;
    t390 = t64*t4+t123*t42+t38*t9+t76*t4+t43*t27+t48*t27+t149*t17+t139*t18+t145
*t10+t243*t18+t29*t167;
    t420 = 2.0*t105*t17*t21+2.0*t203*t10+4.0*t103*t111+2.0*t26*t106+2.0*t26*
t167+2.0*t94*t119*t14+2.0*t94*t9*t21+2.0*t127*t47+2.0*t4*t51+4.0*t103*t152+4.0*
t99*t159+2.0*t21*t8*t24;
    grads[6] = t187*(2.0*t188*(t38*t2+t149*t12+t21*t1)-t196*(2.0*t390+t420))/
2.0;
    t435 = t63*t8;
    t447 = t52*t8*t57+t55*t8*t54+t435*t57+t1*t54+t435*t54+t1*t57+t139*t135+t145
*t39+t127*t14*t17+t99*t14*t24+t166*t33;
    t476 = 2.0*t123*t5*t9+2.0*t103*t110*t17+2.0*t103*t5*t24+2.0*t32*t100+4.0*
t120*t94+2.0*t32*t166+4.0*t94*t155+4.0*t105*t163+2.0*t166*t24+2.0*t179*t8+2.0*
t149*t88+2.0*t38*t85;
    grads[7] = t187*(2.0*t188*(t3*t9+t13*t17+t24*t1)-t196*(2.0*t447+t476))/2.0;
    return;
  }
}

